### ISSUE TITLE
Move this repo to huaweicloud organization

### ISSUE THREAD

**Issue by gberche-orange** [zhongjun2/bosh-huaweicloud-cpi-release#24]
[Transferring](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/) this repo to an official huawei github organization (https://github.com/huaweicloud) 
* makes it easier to understand this is the official huawei cpi.
* makes it easier to discover it, as it get close to other CF-related repos such as https://github.com/huaweicloud/huaweicloud-service-broker

**Comment by zhongjun2** [comment]
After this repo merged to https://github.com/cloudfoundry-incubator/ , we will fork the huaweicloud cpi from https://github.com/cloudfoundry-incubator/ to https://github.com/huaweicloud.

**Comment by gberche-orange** [comment]
yes, my mistake, sorry for the confusion
